apiVersion: v1
kind: Service
metadata:
  name: qrcodes-api-np-srv
spec:
  type: NodePort
  selector:
    app: qrcodes-api
  ports:
    - name: qrcodes-api
      protocol: TCP
      port: 80
      targetPort: 80