apiVersion: v1
kind: Service
metadata:
  name: links-api-np-srv
spec:
  type: NodePort
  selector:
    app: links-api
  ports:
    - name: links-api
      protocol: TCP
      port: 80
      targetPort: 80