apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-links-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-links-api
  template:
    metadata:
      labels:
        app: mongodb-links-api
    spec:
      containers:
        - name: mongodb-links-api
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "pa55word"
            - name: MONGO_INITDB_DATABASE
              value: "linksservice"
          volumeMounts:
            - name: linksservice
              mountPath: /var/opt/linksservice/data
      volumes:
        - name: linksservice
          persistentVolumeClaim:
            claimName: database-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-links-api-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: mongodb-links-api
  ports:
    - name: mongodb-links-api
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-links-api-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: mongodb-links-api
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017