apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-users-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-users-api
  template:
    metadata:
      labels:
        app: postgresql-users-api
    spec:
      containers:
        - name: postgresql-users-api
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: POSTGRES_DB
              value: "usersservice"
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_PASSWORD
              value: "pa55word"
          volumeMounts:
            - mountPath: /var/opt/postgresql-users/data
              name: postgresql-users
      volumes:
        - name: postgresql-users
          persistentVolumeClaim:
            claimName: database-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-users-api-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: postgresql-users-api
  ports:
    - name: postgresql-users-api
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-users-api-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: postgresql-users-api
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432