apiVersion: v1
kind: Service
metadata:
  name: users-api-np-srv
spec:
  type: NodePort
  selector:
    app: users-api
  ports:
    - name: users-api
      protocol: TCP
      port: 80
      targetPort: 80